export class Cards {
  cards = [
    {
      id: '1',
      name: 'Шут',
      type: 'senior-arcans',
      image: 'fool.jpg',
      text: 'Шут'
    },
    {
      id: '2',
      name: 'Маг',
      type: 'senior-arcans',
      image: 'mag.jpg',
    },
    {
      id: '3',
      name: 'Жрица',
      type: 'senior-arcans',
      image: 'priestess.jpg',
    },
    {
      id: '4',
      name: 'Императрица',
      type: 'senior-arcans',
      image: 'empress.jpg',
    },
    {
      id: '5',
      name: 'Император',
      type: 'senior-arcans',
      image: 'emperor.jpg',
    },
    {
      id: '6',
      name: 'Верховный жрец',
      type: 'senior-arcans',
      image: 'high-priest.jpg',
    },
    {
      id: '7',
      name: 'Влюбленные',
      type: 'senior-arcans',
      image: 'lovers.jpg',
    },
    {
      id: '8',
      name: 'Колесница',
      type: 'senior-arcans',
      image: 'chariot.jpg',
    },
    {
      id: '9',
      name: 'Правосудие',
      type: 'senior-arcans',
      image: 'justice.jpg',
    },
    {
      id: '10',
      name: 'Отшельник',
      type: 'senior-arcans',
      image: 'hermit.jpg',
    },
    {
      id: '11',
      name: 'Колесо Фортуны',
      type: 'senior-arcans',
      image: 'wheel-fortune.jpg',
    },
    {
      id: '12',
      name: 'Сила',
      type: 'senior-arcans',
      image: 'power.jpg',
    },
    {
      id: '13',
      name: 'Повешенный',
      type: 'senior-arcans',
      image: 'hanged.jpg',
    },
    {
      id: '14',
      name: 'Смерть',
      type: 'senior-arcans',
      image: 'death.jpg',
    },
    {
      id: '15',
      name: 'Умеренность',
      type: 'senior-arcans',
      image: 'moderation.jpg',
    },
    {
      id: '16',
      name: 'Дьявол',
      type: 'senior-arcans',
      image: 'devil.jpg',
    },
    {
      id: '17',
      name: 'Башня',
      type: 'senior-arcans',
      image: 'tower.jpg',
    },
    {
      id: '18',
      name: 'Звезда',
      type: 'senior-arcans',
      image: 'star.jpg',
    },
    {
      id: '19',
      name: 'Луна',
      type: 'senior-arcans',
      image: 'moon.jpg',
    },
    {
      id: '20',
      name: 'Солнце',
      type: 'senior-arcans',
      image: 'sun.jpg',
    },
    {
      id: '21',
      name: 'Страшный суд',
      type: 'senior-arcans',
      image: 'last-judgment.jpg',
    },
    {
      id: '22',
      name: 'Мир',
      type: 'senior-arcans',
      image: 'world.jpg',
    },
    // жезл
    {
      id: '23',
      name: '2 жезлов',
      type: 'wands',
      image: '2-wands.jpg',
    },
    {
      id: '24',
      name: '3 жезлов',
      type: 'wands',
      image: '3-wands.jpg',
    },
    {
      id: '25',
      name: '4 жезлов',
      type: 'wands',
      image: '4-wands.jpg',
    },
    {
      id: '26',
      name: '5 жезлов',
      type: 'wands',
      image: '5-wands.jpg',
    },
    {
      id: '27',
      name: '6 жезлов',
      type: 'wands',
      image: '6-wands.jpg',
    },
    {
      id: '28',
      name: '7 жезлов',
      type: 'wands',
      image: '7-wands.jpg',
    },
    {
      id: '29',
      name: '8 жезлов',
      type: 'wands',
      image: '8-wands.jpg',
    },
    {
      id: '30',
      name: '9 жезлов',
      type: 'wands',
      image: '9-wands.jpg',
    },
    {
      id: '31',
      name: '10 жезлов',
      type: 'wands',
      image: '10-wands.jpg',
    },
    {
      id: '32',
      name: 'Паж жезлов',
      type: 'wands',
      image: 'page-wands.jpg',
    },
    {
      id: '33',
      name: 'Рыцарь жезлов',
      type: 'wands',
      image: 'knight-wands.jpg',
    },
    {
      id: '34',
      name: 'Королева жезлов',
      type: 'wands',
      image: 'queen-wands.jpg',
    },
    {
      id: '35',
      name: 'Король жезлов',
      type: 'wands',
      image: 'king-wands.jpg',
    },
    {
      id: '36',
      name: 'Туз жезлов',
      type: 'wands',
      image: 'ace-wands.jpg',
    },
    // куб
    {
      id: '37',
      name: '2 кубков',
      type: 'cups',
      image: '2-cups.jpg',
    },
    {
      id: '38',
      name: '3 кубков',
      type: 'cups',
      image: '3-cups.jpg',
    },
    {
      id: '39',
      name: '4 кубков',
      type: 'cups',
      image: '4-cups.jpg',
    },
    {
      id: '40',
      name: '5 кубков',
      type: 'cups',
      image: '5-cups.jpg',
    },
    {
      id: '41',
      name: '6 кубков',
      type: 'cups',
      image: '6-cups.jpg',
    },
    {
      id: '42',
      name: '7 кубков',
      type: 'cups',
      image: '7-cups.jpg',
    },
    {
      id: '43',
      name: '8 кубков',
      type: 'cups',
      image: '8-cups.jpg',
    },
    {
      id: '44',
      name: '9 кубков',
      type: 'cups',
      image: '9-cups.jpg',
    },
    {
      id: '45',
      name: '10 кубков',
      type: 'cups',
      image: '10-cups.jpg',
    },
    {
      id: '46',
      name: 'Паж кубков',
      type: 'cups',
      image: 'page-cups.jpg',
    },
    {
      id: '47',
      name: 'Рыцарь кубков',
      type: 'cups',
      image: 'knight-cups.jpg',
    },
    {
      id: '48',
      name: 'Королева кубков',
      type: 'cups',
      image: 'queen-cups.jpg',
    },
    {
      id: '49',
      name: 'Король кубков',
      type: 'cups',
      image: 'king-cups.jpg',
    },
    {
      id: '50',
      name: 'Туз кубков',
      type: 'cups',
      image: 'ace-cups.jpg',
    },
    // меч
    {
      id: '51',
      name: '2 мечей',
      type: 'sword',
      image: '2-sword.jpg',
    },
    {
      id: '52',
      name: '3 мечей',
      type: 'sword',
      image: '3-sword.jpg',
    },
    {
      id: '53',
      name: '4 мечей',
      type: 'sword',
      image: '4-sword.jpg',
    },
    {
      id: '54',
      name: '5 мечей',
      type: 'sword',
      image: '5-sword.jpg',
    },
    {
      id: '55',
      name: '6 мечей',
      type: 'sword',
      image: '6-sword.jpg',
    },
    {
      id: '56',
      name: '7 мечей',
      type: 'sword',
      image: '7-sword.jpg',
    },
    {
      id: '57',
      name: '8 мечей',
      type: 'sword',
      image: '8-sword.jpg',
    },
    {
      id: '58',
      name: '9 мечей',
      type: 'sword',
      image: '9-sword.jpg',
    },
    {
      id: '59',
      name: '10 мечей',
      type: 'sword',
      image: '10-sword.jpg',
    },
    {
      id: '60',
      name: 'Паж мечей',
      type: 'sword',
      image: 'page-sword.jpg',
    },
    {
      id: '61',
      name: 'Рыцарь мечей',
      type: 'sword',
      image: 'knight-sword.jpg',
    },
    {
      id: '62',
      name: 'Королева мечей',
      type: 'sword',
      image: 'queen-sword.jpg',
    },
    {
      id: '63',
      name: 'Король мечей',
      type: 'sword',
      image: 'king-sword.jpg',
    },
    {
      id: '64',
      name: 'Туз мечей',
      type: 'sword',
      image: 'ace-sword.jpg',
    },
    // пентакли
    {
      id: '65',
      name: '2 пентаклей',
      type: 'pentacles',
      image: '2-pentacles.jpg',
    },
    {
      id: '66',
      name: '3 пентаклей',
      type: 'pentacles',
      image: '3-pentacles.jpg',
    },
    {
      id: '67',
      name: '4 пентаклей',
      type: 'pentacles',
      image: '4-pentacles.jpg',
    },
    {
      id: '68',
      name: '5 пентаклей',
      type: 'pentacles',
      image: '5-pentacles.jpg',
    },
    {
      id: '69',
      name: '6 пентаклей',
      type: 'pentacles',
      image: '6-pentacles.jpg',
    },
    {
      id: '70',
      name: '7 пентаклей',
      type: 'pentacles',
      image: '7-pentacles.jpg',
    },
    {
      id: '71',
      name: '8 пентаклей',
      type: 'pentacles',
      image: '8-pentacles.jpg',
    },
    {
      id: '72',
      name: '9 пентаклей',
      type: 'pentacles',
      image: '9-pentacles.jpg',
    },
    {
      id: '73',
      name: '10 пентаклей',
      type: 'pentacles',
      image: '10-pentacles.jpg',
    },
    {
      id: '74',
      name: 'Паж пентаклей',
      type: 'pentacles',
      image: 'page-pentacles.jpg',
    },
    {
      id: '75',
      name: 'Рыцарь пентаклей',
      type: 'pentacles',
      image: 'knight-pentacles.jpg',
    },
    {
      id: '76',
      name: 'Королева пентаклей',
      type: 'pentacles',
      image: 'queen-pentacles.jpg',
    },
    {
      id: '77',
      name: 'Король пентаклей',
      type: 'pentacles',
      image: 'king-pentacles.jpg',
    },
    {
      id: '78',
      name: 'Туз пентаклей',
      type: 'pentacles',
      image: 'ace-pentacles.jpg',
    }
  ];
}
